services:
  - type: worker
    name: v1xclusive-vouch-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 v1x.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: TOKEN
        sync: false
